### ISSUE TITLE
Cannot find 'SDImageSVGNativeCoder' in scope issue

### ISSUE THREAD

**Issue by dev-jiwon** [SDWebImage/SDWebImageSVGNativeCoder#2]
I installed this library using SPM.
And when I add coder in SDImageCachesManager, and I get an error message "Cannot find 'SDImageSVGNativeCoder' in scope"

Please check this

thank you

**Comment by netTrekHoffmann** [comment]
Just to help if anyone else gets stuck: 


import SDWebImageSVGNativeCoder

but use

SDImageSVGNativeCoder.shared

**Comment by mooshee** [comment]
@dreampiggy There's no module map so the coder cannot be imported in Swift

**Comment by dreampiggy** [comment]
I'll fix it soon. Seems the Package.swift has some issues.

**Comment by dreampiggy** [comment]
Did you means this linker error ?

<img width="438" alt="截屏2022-09-30 11 24 19" src="https://user-images.githubusercontent.com/6919743/193183561-cabc928b-48b4-4935-b077-ec7ebaa10649.png">

Add `libxml.2.tbd` into the `Link Library and Frameworks` of Xcode. Then the build success.

I can fix this in the https://github.com/SDWebImage/svgnative-Xcode anyway

**Comment by dreampiggy** [comment]
Oh no. It seems the `SDImageSVGNativeCoder` public headers does not added into SwiftPM.


<img width="746" alt="截屏2022-09-30 11 26 26" src="https://user-images.githubusercontent.com/6919743/193183710-8119af1d-17e1-4913-8536-a270086a12e7.png">


So, besides that SVGNative-Xcode repo, still need to fix this repo :)

**Comment by dreampiggy** [comment]
Please have a try with v0.1.1

<img width="1082" alt="截屏2022-09-30 12 07 40" src="https://user-images.githubusercontent.com/6919743/193188309-23f681e6-4a85-4c31-b69c-a0e34beac2bb.png">

**Comment by dev-jiwon** [comment]
> Please have a try with v0.1.1
> 
> <img alt="截屏2022-09-30 12 07 40" width="1082" src="https://user-images.githubusercontent.com/6919743/193188309-23f681e6-4a85-4c31-b69c-a0e34beac2bb.png">

thanks!
