### ISSUE TITLE
image default Color is black

### ISSUE THREAD

**Issue by iPermanent** [SDWebImage/SDWebImageSVGNativeCoder#3]
After change the SVGKit to this lib, the image that show with white background color now display black bg, so can this lib open a interface or property to set the default color?

**Comment by dreampiggy** [comment]
Emmmm


It sounds configuable for the internal SVG-Native codec.

I'll check their API and change the default color to White, which may suitable for most mobile cases.

**Comment by dreampiggy** [comment]
@iPermanent  Can you please provide a sample SVG for me to test ?

**Comment by iPermanent** [comment]
![vvvvv](https://user-images.githubusercontent.com/1712759/193219883-174f1bb0-8b78-4839-95a8-f68853296553.svg)
Here I attached it, in my project, I load it with url, and with sdwebimage to show the svg,url is https://preview.yutangim.cn/avatar/vvvvv?custom=true&color=F6303A

**Comment by dreampiggy** [comment]
It not the background color.

The current Adobe's svg-native, seems can not parse when an `<use>` reference another root node inside `<defs>`

Your SVG looks like:

```xml
<defs>
	<circle id="path-1" cx="100" cy="100" r="100"></circle>
</defs>
<use fill-opacity="0.05" fill="#2196F3" xlink:href="#path-1"></use>
```

Which should be parsed as such a node:

```xml
<circle id="path-1" cx="100" cy="100" r="100" fill-opacity="0.05" fill="#2196F3"></circle>
```

**Comment by dreampiggy** [comment]
We can fire issue to Adobe's svg-native first.

For workaround, just change the SVG into this type, without those usage combined with `defs` and `use`

---

Fired https://github.com/adobe/svg-native-viewer/issues/182

**Comment by dreampiggy** [comment]
Please use [v0.2.0](https://github.com/SDWebImage/SDWebImageSVGNativeCoder/releases/tag/0.2.0) to test again.

Close fow now. Feel free to re-open if you need.
