### ISSUE TITLE
CoreGraphics

### ISSUE THREAD

**Issue by iDevelopper** [SDWebImage/SDWebImageSVGNativeCoder#5]
WatchOS:

Undefined symbols for all functions from CoreGraphics when install via CocoaPods.

Have to add the framework manually to the pod.

**Comment by iDevelopper** [comment]
Ping... Any update?

**Comment by dreampiggy** [comment]
Please use [v0.2.0](https://github.com/SDWebImage/SDWebImageSVGNativeCoder/releases/tag/0.2.0) to test again.

Close fow now. Feel free to re-open if you need.
