### ISSUE TITLE
svg show error

### ISSUE THREAD

**Issue by nba88719840** [SDWebImage/SDWebImageSVGNativeCoder#6]
<img width="1138" alt="image" src="https://github.com/SDWebImage/SDWebImageSVGNativeCoder/assets/6261850/5c4aea8f-66d0-424e-b003-a4f27cf6360b">
demo use https://jys-dev.oss-cn-hongkong.aliyuncs.com/default/platform/icon/vip1.svg

**Comment by susonthapa** [comment]
I'm running into similar issues as well. When I try to render [this](https://raw.githubusercontent.com/bumptech/glide/master/samples/svg/src/main/res/raw/android_toy_h.svg) image I get this.

## Using this library
![SCR-20230716-kjlq](https://github.com/SDWebImage/SDWebImageSVGNativeCoder/assets/33973551/1e0021bd-6864-4d2a-b7ce-a8c4b928fd17)

## Actual Image
<img width="644" alt="image" src="https://github.com/SDWebImage/SDWebImageSVGNativeCoder/assets/33973551/849610c8-82ad-4a42-adb5-2a38a8052215">

Using SVGKit shows everything correctly though.

**Comment by dreampiggy** [comment]
Can you test with the latest svgnative version. ?

**Comment by dreampiggy** [comment]
Please use [v0.2.0](https://github.com/SDWebImage/SDWebImageSVGNativeCoder/releases/tag/0.2.0) to test again.

Close fow now. Feel free to re-open if you need.
