### ISSUE TITLE
watchOS 10 && Xcode 15 issues about compile

### ISSUE THREAD

**Issue by iDevelopper** [SDWebImage/SDWebImageSVGNativeCoder#7]
SDWebImageSVGNativeCoder-watchOS
/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h
/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1105:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

in file included from /Users/patrickbodet/Documents/ShoutRadiosSwiftWatch/Pods/SDWebImageSVGNativeCoder/SDWebImageSVGNativeCoder/Classes/SDImageSVGNativeCoder.mm:9:
in file included from /Users/patrickbodet/Documents/ShoutRadiosSwiftWatch/Pods/SDWebImageSVGNativeCoder/SDWebImageSVGNativeCoder/Classes/SDImageSVGNativeCoder.h:10:
in file included from /Users/patrickbodet/Documents/ShoutRadiosSwiftWatch/Pods/SDWebImage/WebImage/SDWebImage.h:10:
in file included from /Users/patrickbodet/Documents/ShoutRadiosSwiftWatch/Pods/SDWebImage/SDWebImage/Core/SDWebImageCompat.h:70:
in file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/System/Library/Frameworks/WatchKit.framework/Headers/WatchKit.h:40:
in file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/System/Library/Frameworks/WatchKit.framework/Headers/WKInterfaceSCNScene.h:11:
in file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/System/Library/Frameworks/SceneKit.framework/Headers/SceneKit.h:14:
in file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/System/Library/Frameworks/SceneKit.framework/Headers/SceneKitTypes.h:10:
in file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/simd.h:23:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1105:25 Use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1120:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1120:25 Use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1121:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1121:25 Use of undeclared identifier 'vzip2q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1134:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1134:25 Use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1135:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1135:25 Use of undeclared identifier 'vzip2q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1154:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1154:24 Use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1155:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1155:24 Use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1156:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1156:24 Use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1157:17 No viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1157:24 Use of undeclared identifier 'vzip2q_f32'; did you mean 'vzipq_f32'?

/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS10.0.sdk/usr/include/simd/matrix.h:1178:24 Use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

/Users/patrickbodet/Documents/ShoutRadiosSwiftWatch/Pods/SDWebImageSVGNativeCoder/SDWebImageSVGNativeCoder/Classes/SDImageSVGNativeCoder.mm
/Users/patrickbodet/Documents/ShoutRadiosSwiftWatch/Pods/SDWebImageSVGNativeCoder/SDWebImageSVGNativeCoder/Classes/SDImageSVGNativeCoder.mm too many errors emitted, stopping now

**Comment by iDevelopper** [comment]
Ping ! Are you planning an update?

**Comment by dreampiggy** [comment]
I don't think this error related to SDWebImage or SVG-native library ?

Seems some bugs from Apple' SDK header, not us. They use the `simd` header contains issues on watchOS.

**Comment by dreampiggy** [comment]
And I think your issue title is wrong. It's not `iOS 17`

It's `watchOS 10`

**Comment by dreampiggy** [comment]
The lib build success on iOS 17 SDK and Xcode 15
![image](https://github.com/SDWebImage/SDWebImageSVGNativeCoder/assets/6919743/7e9f8601-956e-4da1-a6d7-d265d6314b0c)
