### ISSUE TITLE
Xcode 15 crash

### ISSUE THREAD

**Issue by MiaoMiaoai** [SDWebImage/SDWebImageSVGNativeCoder#8]
![截屏2023-11-24 09 29 07](https://github.com/SDWebImage/SDWebImageSVGNativeCoder/assets/19339100/f695b281-acf0-4096-bc4e-f16726c4d71f)
![截屏2023-11-24 09 28 55](https://github.com/SDWebImage/SDWebImageSVGNativeCoder/assets/19339100/8968ab0a-e325-4fd1-b96a-45a0e4f92cf3)

**Comment by dreampiggy** [comment]
Apple's Bug on libc++ (C++ standard library). Using Xcode 15.1+
